version: '3.8'
services:
  edu365:
    container_name: edu365-search
    image: edu365-search
    build:
      context: .
      dockerfile: Dockerfile
    command: node api/server.js
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ${PWD}/credentials:/usr/src/app/credentials
      - ${PWD}/log:/usr/src/app/log
      - ${PWD}/.env:/usr/src/app/.env

      